"""
Code Generator - Forge Your Creation
Generates complete OLMo-core compatible model configurations and training scripts.

"I used to generate PyTorch code from scratch like you, then I took an OLMo-core
import to the knee."
"""

from datetime import datetime
from .config import (
    ModelConfig,
    SequenceModelType,
    AttentionType,
    AttentionBackend,
    MLPType,
    BlockType,
    NormType,
    PositionEncoding,
    RoPEScaling,
    Optimizer,
    MoEGatingFunction,
)


def generate_olmo_config(config: ModelConfig) -> str:
    """Generate OLMo-core TransformerConfig code."""
    model_name = config.name.replace("-", "").replace(" ", "")

    # Determine attention backend
    backend_map = {
        AttentionBackend.TORCH: "AttentionBackend.torch",
        AttentionBackend.FLASH_2: "AttentionBackend.flash_2",
        AttentionBackend.FLASH_3: "AttentionBackend.flash_3",
        AttentionBackend.FLASH_4: "AttentionBackend.flash_4",
        AttentionBackend.TRANSFORMER_ENGINE: "AttentionBackend.te",
    }
    backend = backend_map.get(config.attention_backend, "AttentionBackend.torch")

    # Determine block type
    block_map = {
        BlockType.PRE_NORM: "TransformerBlockConfig",
        BlockType.REORDERED: "ReorderedNormTransformerBlockConfig",
        BlockType.PERI_NORM: "PeriNormTransformerBlockConfig",
        BlockType.NORMALIZED: "NormalizedTransformerBlockConfig",
        BlockType.MOE: "MoETransformerBlockConfig",
        BlockType.MOE_REORDERED: "MoEReorderedNormTransformerBlockConfig",
        BlockType.MOE_HYBRID: "MoEHybridTransformerBlockConfig",
    }
    block_config = block_map.get(config.block_type, "TransformerBlockConfig")

    # Determine norm type
    norm_map = {
        NormType.LAYER_NORM: "LayerNormConfig()",
        NormType.RMS_NORM: "RMSNormConfig()",
        NormType.FUSED_RMS_NORM: "FusedRMSNormConfig()",
        NormType.L2_NORM: "L2NormConfig()",
    }
    norm_config = norm_map.get(config.norm_type, "RMSNormConfig()")

    # RoPE configuration
    rope_config = ""
    if config.position_encoding in (PositionEncoding.ROPE, PositionEncoding.FUSED_ROPE, PositionEncoding.COMPLEX_ROPE):
        rope_type = "RoPEType.default"
        if config.position_encoding == PositionEncoding.FUSED_ROPE:
            rope_type = "RoPEType.fused"
        elif config.position_encoding == PositionEncoding.COMPLEX_ROPE:
            rope_type = "RoPEType.complex"

        rope_scaling = ""
        if config.rope_scaling != RoPEScaling.NONE:
            scaling_map = {
                RoPEScaling.ABF: "RoPEScalingConfig(name='abf')",
                RoPEScaling.PI: "RoPEScalingConfig(name='pi')",
                RoPEScaling.LLAMA3: "RoPEScalingConfig(name='llama3')",
                RoPEScaling.YARN: "RoPEScalingConfig(name='yarn')",
            }
            rope_scaling = f",\n        scaling={scaling_map.get(config.rope_scaling, '')}"

        rope_config = f"""
    rope=RoPEConfig(
        type={rope_type},
        theta={config.rope_theta}{rope_scaling}
    ),"""

    # MoE configuration
    moe_config = ""
    if config.is_moe:
        gating = "softmax" if config.moe_gating == MoEGatingFunction.SOFTMAX else "sigmoid"
        moe_config = f"""
    moe=MoEConfig(
        num_experts={config.num_experts},
        top_k={config.experts_per_token},
        router=MoELinearRouterConfig(gating="{gating}"),
        lb_loss_weight={config.moe_lb_weight} if {config.moe_load_balancing} else 0.0,
        z_loss_weight={config.moe_z_loss_weight},
        shared_mlp={config.moe_shared_mlp},
    ),"""

    # Attention configuration
    attn_type = "AttentionConfig"
    if config.attention_type == AttentionType.FUSED:
        attn_type = "FusedAttentionConfig"
    elif config.attention_type == AttentionType.NORMALIZED:
        attn_type = "NormalizedAttentionConfig"

    return f'''"""
{config.name} - OLMo-core Model Configuration
{'=' * 60}
Race: {config.race}
Parameters: ~{config.param_str()}

Generated by The Elder Models V: LLMRIM
"Fus Ro Brrr... Your training begins."

Architecture:
- Sequence Model: {config.sequence_model.name}
- Attention: {config.attention_type.name}
- MLP: {config.mlp_type.name}
- Block: {config.block_type.name}
- Norm: {config.norm_type.name}
- Position: {config.position_encoding.name}
{'- MoE: ' + str(config.num_experts) + ' experts, top-' + str(config.experts_per_token) if config.is_moe else ''}
"""

from olmo_core.nn.transformer import (
    TransformerConfig,
    TransformerBlockConfig,
    {block_config if block_config != "TransformerBlockConfig" else ""}
)
from olmo_core.nn.attention import (
    AttentionConfig,
    {attn_type if attn_type != "AttentionConfig" else ""}
    AttentionBackend,
)
from olmo_core.nn.feed_forward import FeedForwardConfig
from olmo_core.nn.layer_norm import RMSNormConfig, LayerNormConfig, FusedRMSNormConfig, L2NormConfig
from olmo_core.nn.rope import RoPEConfig, RoPEType, RoPEScalingConfig
from olmo_core.nn.lm_head import LMHeadConfig
{"from olmo_core.nn.moe import MoEConfig, MoELinearRouterConfig" if config.is_moe else ""}
{"from olmo_core.nn.fla import FLAConfig, FLAModelConfig" if config.is_mamba or config.is_hybrid else ""}


def build_{model_name.lower()}_config() -> TransformerConfig:
    """Build the {config.name} model configuration."""

    d_model = {config.n_embd}
    n_layers = {config.n_layers}
    n_heads = {config.n_heads}
    n_kv_heads = {config.kv_heads}
    vocab_size = {config.vocab_size}
    max_seq_len = {config.seq_length}

    # Calculate MLP hidden dimension
    mlp_hidden = int(d_model * {config.mlp_ratio})
    {"mlp_hidden = ((mlp_hidden + 255) // 256) * 256  # Round to 256 for efficiency" if config.mlp_type == MLPType.SWIGLU else ""}

    return TransformerConfig(
        d_model=d_model,
        n_layers=n_layers,
        n_heads=n_heads,
        n_kv_heads=n_kv_heads,
        vocab_size=vocab_size,
        max_seq_len=max_seq_len,

        # Attention configuration
        attention={attn_type}(
            n_heads=n_heads,
            n_kv_heads=n_kv_heads,
            head_dim=d_model // n_heads,
            bias={config.attention_bias},
            qk_norm={config.qk_norm},
            dropout={config.attention_dropout},
            backend={backend},
        ),

        # Feed-forward configuration
        feed_forward=FeedForwardConfig(
            hidden_size=mlp_hidden,
            bias={config.mlp_bias},
            {"activation='silu',  # SwiGLU" if config.mlp_type == MLPType.SWIGLU else "activation='gelu',"}
        ),

        # Normalization
        layer_norm={norm_config},

        # Block configuration
        block={block_config}(),{rope_config}{moe_config}

        # LM Head
        lm_head=LMHeadConfig(
            tie_weights={config.tie_embeddings},
        ),

        # Efficiency options
        init_seed=42,
    )


# Build the configuration
config = build_{model_name.lower()}_config()

if __name__ == "__main__":
    from olmo_core.nn.transformer import Transformer

    # Build the model
    model = config.build()
    n_params = sum(p.numel() for p in model.parameters())
    print(f"{config.name}: {{n_params:,}} parameters")
'''


def generate_fla_config(config: ModelConfig) -> str:
    """Generate FLA (Mamba/DeltaNet) model configuration."""
    model_name = config.name.replace("-", "").replace(" ", "")

    # Determine FLA type
    fla_type_map = {
        SequenceModelType.MAMBA: "Mamba",
        SequenceModelType.MAMBA2: "Mamba2",
        SequenceModelType.GATED_DELTANET: "GatedDeltaNet",
    }
    fla_type = fla_type_map.get(config.sequence_model, "Mamba2")

    return f'''"""
{config.name} - OLMo-core FLA Model Configuration
{'=' * 60}
Race: {config.race}
Parameters: ~{config.param_str()}

Generated by The Elder Models V: LLMRIM
"The Dwemer vanished, but their automatons remain..."

Architecture:
- Sequence Model: {config.sequence_model.name}
- FLA Type: {fla_type}
- Norm: {config.norm_type.name}
"""

from olmo_core.nn.fla import FLAConfig, FLABlock, FLAModelConfig
from olmo_core.nn.layer_norm import RMSNormConfig
from olmo_core.nn.lm_head import LMHeadConfig
from fla.layers import {fla_type}


def build_{model_name.lower()}_config():
    """Build the {config.name} FLA model configuration."""

    d_model = {config.n_embd}
    n_layers = {config.n_layers}
    vocab_size = {config.vocab_size}
    max_seq_len = {config.seq_length}

    # FLA layer configuration
    fla_config = FLAConfig(
        name="{fla_type}",
        kwargs=dict(
            d_model=d_model,
            {"d_state=" + str(config.mamba_d_state) + "," if config.sequence_model in (SequenceModelType.MAMBA, SequenceModelType.MAMBA2) else ""}
            {"d_conv=" + str(config.mamba_d_conv) + "," if config.sequence_model in (SequenceModelType.MAMBA, SequenceModelType.MAMBA2) else ""}
            {"expand=" + str(config.mamba_expand) + "," if config.sequence_model in (SequenceModelType.MAMBA, SequenceModelType.MAMBA2) else ""}
        ),
    )

    return FLAModelConfig(
        d_model=d_model,
        n_layers=n_layers,
        vocab_size=vocab_size,
        fla=fla_config,
        layer_norm=RMSNormConfig(),
        lm_head=LMHeadConfig(tie_weights={config.tie_embeddings}),
    )


# Build the configuration
config = build_{model_name.lower()}_config()

if __name__ == "__main__":
    # Build the model
    model = config.build()
    n_params = sum(p.numel() for p in model.parameters())
    print(f"{{config.name}}: {{n_params:,}} parameters")
'''


def generate_hybrid_config(config: ModelConfig) -> str:
    """Generate hybrid (attention + FLA) model configuration."""
    model_name = config.name.replace("-", "").replace(" ", "")

    fla_layers_str = str(config.fla_layers) if config.fla_layers else "list(range(0, n_layers, 2))"

    return f'''"""
{config.name} - OLMo-core Hybrid Model Configuration
{'=' * 60}
Race: {config.race}
Parameters: ~{config.param_str()}

Generated by The Elder Models V: LLMRIM
"The Falmer were twisted by darkness into something new..."

Architecture:
- Sequence Model: HYBRID (Attention + FLA)
- Attention Layers: {config.n_layers - len(config.fla_layers or [])}
- FLA Layers: {len(config.fla_layers or [])}
- Norm: {config.norm_type.name}
"""

from olmo_core.nn.transformer import TransformerConfig, TransformerBlockConfig
from olmo_core.nn.attention import AttentionConfig, AttentionBackend
from olmo_core.nn.feed_forward import FeedForwardConfig
from olmo_core.nn.layer_norm import RMSNormConfig
from olmo_core.nn.rope import RoPEConfig, RoPEType
from olmo_core.nn.lm_head import LMHeadConfig
from olmo_core.nn.fla import FLAConfig, FLABlock


def build_{model_name.lower()}_config():
    """Build the {config.name} hybrid model configuration."""

    d_model = {config.n_embd}
    n_layers = {config.n_layers}
    n_heads = {config.n_heads}
    n_kv_heads = {config.kv_heads}
    vocab_size = {config.vocab_size}
    max_seq_len = {config.seq_length}

    # Layers that use FLA instead of attention
    fla_layers = {fla_layers_str}

    # Build block overrides for FLA layers
    block_overrides = {{}}
    fla_config = FLAConfig(name="GatedDeltaNet", kwargs=dict(d_model=d_model))

    for layer_idx in fla_layers:
        block_overrides[layer_idx] = FLABlock(fla=fla_config)

    # Calculate MLP hidden dimension
    mlp_hidden = int(d_model * {config.mlp_ratio})
    mlp_hidden = ((mlp_hidden + 255) // 256) * 256

    return TransformerConfig(
        d_model=d_model,
        n_layers=n_layers,
        n_heads=n_heads,
        n_kv_heads=n_kv_heads,
        vocab_size=vocab_size,
        max_seq_len=max_seq_len,

        attention=AttentionConfig(
            n_heads=n_heads,
            n_kv_heads=n_kv_heads,
            head_dim=d_model // n_heads,
            bias={config.attention_bias},
            qk_norm={config.qk_norm},
        ),

        feed_forward=FeedForwardConfig(
            hidden_size=mlp_hidden,
            bias={config.mlp_bias},
            activation='silu',
        ),

        layer_norm=RMSNormConfig(),
        block=TransformerBlockConfig(),

        rope=RoPEConfig(
            type=RoPEType.default,
            theta={config.rope_theta},
        ),

        lm_head=LMHeadConfig(tie_weights={config.tie_embeddings}),

        # Block overrides for hybrid architecture
        block_overrides=block_overrides,
    )


# Build the configuration
config = build_{model_name.lower()}_config()

if __name__ == "__main__":
    # Build the model
    model = config.build()
    n_params = sum(p.numel() for p in model.parameters())
    print(f"{{config.name}}: {{n_params:,}} parameters")
'''


def generate_training_script(config: ModelConfig) -> str:
    """Generate a complete training script using OLMo-core."""
    model_name = config.name.replace("-", "").replace(" ", "")

    optimizer_config = ""
    if config.optimizer == Optimizer.ADAMW:
        optimizer_config = f"""
    optimizer=AdamWConfig(
        lr={config.learning_rate},
        weight_decay={config.weight_decay},
        betas=({config.beta1}, {config.beta2}),
    ),"""
    else:
        optimizer_config = f"""
    # Using Muon optimizer (custom implementation)
    optimizer=AdamWConfig(  # Placeholder - swap with Muon
        lr={config.learning_rate},
        weight_decay={config.weight_decay},
    ),"""

    return f'''"""
{config.name} - Training Script
{'=' * 60}
Generated by The Elder Models V: LLMRIM

This script sets up distributed training using OLMo-core.
Modify the data paths and hyperparameters as needed.
"""

import sys
from pathlib import Path

from olmo_core.config import DType
from olmo_core.distributed.parallel import DataParallelConfig, DataParallelType
from olmo_core.nn.transformer import TransformerConfig
from olmo_core.optim import AdamWConfig, CosineWithWarmupConfig
from olmo_core.train import TrainerConfig
from olmo_core.train.callbacks import (
    CheckpointerCallback,
    GarbageCollectorCallback,
    GPUMemoryMonitorCallback,
    GradClipperCallback,
    SchedulerCallback,
)


def build_trainer_config(
    model_config: TransformerConfig,
    run_name: str = "{model_name.lower()}",
    save_folder: str = "./checkpoints",
) -> TrainerConfig:
    """Build the training configuration."""

    return TrainerConfig(
        save_folder=save_folder,
        rank_microbatch_size=4,  # Adjust based on GPU memory
        metrics_collect_interval=10,
        cancel_check_interval=1,

        # Data parallelism
        data_parallel=DataParallelConfig(
            name=DataParallelType.fsdp,
            param_dtype=DType.bfloat16,
            reduce_dtype=DType.float32,
        ),
{optimizer_config}
        # Learning rate schedule
        scheduler=CosineWithWarmupConfig(
            warmup_steps=2000,
            t_max=100000,  # Total steps
            alpha_f=0.1,  # Final LR multiplier
        ),

        # Callbacks
        callbacks={{
            "lr_scheduler": SchedulerCallback(),
            "grad_clipper": GradClipperCallback(max_grad_norm=1.0),
            "gpu_monitor": GPUMemoryMonitorCallback(),
            "garbage_collector": GarbageCollectorCallback(),
            "checkpointer": CheckpointerCallback(
                save_interval=1000,
                ephemeral_save_interval=100,
            ),
        }},

        # Compilation (optional, for speed)
        compile_model=True,
    )


if __name__ == "__main__":
    from {model_name.lower()}_config import config as model_config

    trainer_config = build_trainer_config(model_config)

    print(f"Training configuration for {config.name}:")
    print(f"  - Model: ~{config.param_str()} parameters")
    print(f"  - Optimizer: {config.optimizer.name}")
    print(f"  - Learning rate: {config.learning_rate}")
'''


def generate_model_code(config: ModelConfig) -> str:
    """Generate complete model code based on architecture type."""
    if config.is_mamba and not config.is_hybrid:
        return generate_fla_config(config)
    elif config.is_hybrid:
        return generate_hybrid_config(config)
    else:
        return generate_olmo_config(config)


def generate_full_package(config: ModelConfig) -> dict[str, str]:
    """Generate a complete package with config, model, and training script."""
    model_name = config.name.replace("-", "").replace(" ", "").lower()

    return {
        f"{model_name}_config.py": generate_model_code(config),
        f"{model_name}_train.py": generate_training_script(config),
        "README.md": _generate_readme(config),
    }


def _generate_readme(config: ModelConfig) -> str:
    """Generate a README for the model."""
    return f"""# {config.name}

Generated by **The Elder Models V: LLMRIM**

*"Fus Ro Brrr... Your training begins."*

## Architecture

| Attribute | Value |
|-----------|-------|
| Race | {config.race} |
| Parameters | ~{config.param_str()} |
| Sequence Model | {config.sequence_model.name} |
| Attention | {config.attention_type.name} |
| MLP | {config.mlp_type.name} |
| Block | {config.block_type.name} |
| Norm | {config.norm_type.name} |
| Position | {config.position_encoding.name} |
| Context Length | {config.seq_length:,} |
| Vocabulary | {config.vocab_size:,} |

## Configuration

- **Embedding Dimension**: {config.n_embd}
- **Layers**: {config.n_layers}
- **Attention Heads**: {config.n_heads}
- **KV Heads**: {config.kv_heads}

{f"## Mixture of Experts" if config.is_moe else ""}
{f"- **Experts**: {config.num_experts}" if config.is_moe else ""}
{f"- **Experts per Token**: {config.experts_per_token}" if config.is_moe else ""}

## Usage

```python
from {config.name.replace('-', '').replace(' ', '').lower()}_config import config

# Build the model
model = config.build()

# Count parameters
n_params = sum(p.numel() for p in model.parameters())
print(f"Parameters: {{n_params:,}}")
```

## Training

```bash
# Single GPU
python {config.name.replace('-', '').replace(' ', '').lower()}_train.py

# Multi-GPU with torchrun
torchrun --nproc_per_node=8 {config.name.replace('-', '').replace(' ', '').lower()}_train.py
```

## Requirements

- Python 3.10+
- PyTorch 2.0+
- olmo-core
- flash-attn (optional, for Flash Attention)
- fla (for Mamba/linear attention models)

---

*Generated on {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}*
"""
