"""
Code Generator - Forge Your Creation
Generates complete OLMo-core compatible model configurations and training scripts.

Updated for OLMo-core v2.4.0+ SequenceMixer API:
- Uses sequence_mixer= field instead of deprecated attention= field
- Native GatedDeltaNetConfig for linear attention models
- Proper block_overrides for hybrid architectures

"I used to generate PyTorch code from scratch like you, then I took an OLMo-core
import to the knee."
"""

from datetime import datetime
from .config import (
    ModelConfig,
    SequenceModelType,
    AttentionType,
    AttentionBackend,
    MLPType,
    BlockType,
    NormType,
    PositionEncoding,
    RoPEScaling,
    Optimizer,
    MoEGatingFunction,
)


def generate_olmo_config(config: ModelConfig) -> str:
    """Generate OLMo-core TransformerConfig code using SequenceMixer API."""
    model_name = config.name.replace("-", "").replace(" ", "")

    # Determine attention backend
    backend_map = {
        AttentionBackend.TORCH: "AttentionBackend.torch",
        AttentionBackend.FLASH_2: "AttentionBackend.flash_2",
        AttentionBackend.FLASH_3: "AttentionBackend.flash_3",
        AttentionBackend.FLASH_4: "AttentionBackend.flash_4",
        AttentionBackend.TRANSFORMER_ENGINE: "AttentionBackend.te",
    }
    backend = backend_map.get(config.attention_backend, "AttentionBackend.torch")

    # Determine block type
    block_type_map = {
        BlockType.PRE_NORM: "TransformerBlockType.default",
        BlockType.REORDERED: "TransformerBlockType.reordered_norm",
        BlockType.PERI_NORM: "TransformerBlockType.peri_norm",
        BlockType.NORMALIZED: "TransformerBlockType.normalized",
        BlockType.MOE: "TransformerBlockType.moe",
        BlockType.MOE_REORDERED: "TransformerBlockType.moe_reordered_norm",
        BlockType.MOE_HYBRID: "TransformerBlockType.moe_hybrid",
    }
    block_type = block_type_map.get(config.block_type, "TransformerBlockType.default")

    # Determine norm type
    norm_map = {
        NormType.LAYER_NORM: "LayerNormConfig()",
        NormType.RMS_NORM: "RMSNormConfig()",
        NormType.FUSED_RMS_NORM: "FusedRMSNormConfig()",
        NormType.L2_NORM: "L2NormConfig()",
    }
    norm_config = norm_map.get(config.norm_type, "RMSNormConfig()")

    # RoPE configuration
    rope_config = ""
    if config.position_encoding in (PositionEncoding.ROPE, PositionEncoding.FUSED_ROPE, PositionEncoding.COMPLEX_ROPE):
        rope_type = "RoPEType.default"
        if config.position_encoding == PositionEncoding.FUSED_ROPE:
            rope_type = "RoPEType.fused"
        elif config.position_encoding == PositionEncoding.COMPLEX_ROPE:
            rope_type = "RoPEType.complex"

        rope_scaling = ""
        if config.rope_scaling != RoPEScaling.NONE:
            scaling_map = {
                RoPEScaling.ABF: "RoPEScalingConfig(name='abf')",
                RoPEScaling.PI: "RoPEScalingConfig(name='pi')",
                RoPEScaling.LLAMA3: "RoPEScalingConfig(name='llama3')",
                RoPEScaling.YARN: "RoPEScalingConfig(name='yarn')",
            }
            rope_scaling = f",\n            scaling={scaling_map.get(config.rope_scaling, '')}"

        rope_config = f"""
        rope=RoPEConfig(
            type={rope_type},
            theta={config.rope_theta}{rope_scaling}
        ),"""

    # MoE configuration
    moe_config = ""
    if config.is_moe:
        gating = "softmax" if config.moe_gating == MoEGatingFunction.SOFTMAX else "sigmoid"
        moe_config = f"""
        moe=MoEConfig(
            num_experts={config.num_experts},
            top_k={config.experts_per_token},
            router=MoELinearRouterConfig(gating="{gating}"),
            lb_loss_weight={config.moe_lb_weight} if {config.moe_load_balancing} else 0.0,
            z_loss_weight={config.moe_z_loss_weight},
            shared_mlp={config.moe_shared_mlp},
        ),"""

    # Attention configuration (now as sequence_mixer)
    attn_type = "AttentionConfig"
    if config.attention_type == AttentionType.FUSED:
        attn_type = "FusedAttentionConfig"
    elif config.attention_type == AttentionType.NORMALIZED:
        attn_type = "NormalizedAttentionConfig"

    # Build extra imports
    extra_imports = []
    if attn_type != "AttentionConfig":
        extra_imports.append(attn_type)
    if config.is_moe:
        extra_imports.append("# MoE imports below")

    return f'''"""
{config.name} - OLMo-core Model Configuration
{'=' * 60}
Race: {config.race}
Parameters: ~{config.param_str()}

Generated by The Elder Models V: LLMRIM
"Fus Ro Brrr... Your training begins."

Architecture:
- Sequence Model: {config.sequence_model.name}
- Sequence Mixer: {config.attention_type.name} (SequenceMixer API)
- MLP: {config.mlp_type.name}
- Block: {config.block_type.name}
- Norm: {config.norm_type.name}
- Position: {config.position_encoding.name}
{'- MoE: ' + str(config.num_experts) + ' experts, top-' + str(config.experts_per_token) if config.is_moe else ''}
"""

from olmo_core.nn.transformer import (
    TransformerConfig,
    TransformerBlockConfig,
    TransformerBlockType,
)
from olmo_core.nn.attention import (
    AttentionConfig,
    {attn_type + "," if attn_type != "AttentionConfig" else ""}
    AttentionBackend,
)
from olmo_core.nn.feed_forward import FeedForwardConfig
from olmo_core.nn.layer_norm import RMSNormConfig, LayerNormConfig, FusedRMSNormConfig, L2NormConfig
from olmo_core.nn.rope import RoPEConfig, RoPEType, RoPEScalingConfig
from olmo_core.nn.lm_head import LMHeadConfig
{"from olmo_core.nn.moe import MoEConfig, MoELinearRouterConfig" if config.is_moe else ""}


def build_{model_name.lower()}_config() -> TransformerConfig:
    """Build the {config.name} model configuration."""

    d_model = {config.n_embd}
    n_layers = {config.n_layers}
    n_heads = {config.n_heads}
    n_kv_heads = {config.kv_heads}
    vocab_size = {config.vocab_size}
    max_seq_len = {config.seq_length}

    # Calculate MLP hidden dimension
    mlp_hidden = int(d_model * {config.mlp_ratio})
    {"mlp_hidden = ((mlp_hidden + 255) // 256) * 256  # Round to 256 for efficiency" if config.mlp_type == MLPType.SWIGLU else ""}

    return TransformerConfig(
        d_model=d_model,
        n_layers=n_layers,
        vocab_size=vocab_size,

        # Block configuration with SequenceMixer API
        block=TransformerBlockConfig(
            # Attention as sequence mixer (olmo-core v2.4.0+)
            sequence_mixer={attn_type}(
                n_heads=n_heads,
                n_kv_heads=n_kv_heads,
                head_dim=d_model // n_heads,
                bias={config.attention_bias},
                qk_norm={config.qk_norm},
                dropout={config.attention_dropout},
                backend={backend},
            ),

            # Feed-forward configuration
            feed_forward=FeedForwardConfig(
                hidden_size=mlp_hidden,
                bias={config.mlp_bias},
                {"activation='silu',  # SwiGLU" if config.mlp_type == MLPType.SWIGLU else "activation='gelu',"}
            ),

            # Normalization
            layer_norm={norm_config},
        ),{rope_config}{moe_config}

        # LM Head
        lm_head=LMHeadConfig(
            tie_weights={config.tie_embeddings},
        ),

        # Efficiency options
        init_seed=42,
    )


# Build the configuration
config = build_{model_name.lower()}_config()

if __name__ == "__main__":
    from olmo_core.nn.transformer import Transformer

    # Build the model
    model = config.build()
    n_params = sum(p.numel() for p in model.parameters())
    print(f"{config.name}: {{n_params:,}} parameters")
'''


def generate_gdn_config(config: ModelConfig) -> str:
    """Generate native GatedDeltaNet model using olmo-core SequenceMixer API.

    Uses TransformerConfig with GatedDeltaNetConfig as the sequence_mixer,
    which is the native olmo-core approach (no FLA wrapper needed).
    """
    model_name = config.name.replace("-", "").replace(" ", "")

    # Determine norm type
    norm_map = {
        NormType.LAYER_NORM: "LayerNormConfig()",
        NormType.RMS_NORM: "RMSNormConfig()",
        NormType.FUSED_RMS_NORM: "FusedRMSNormConfig()",
        NormType.L2_NORM: "L2NormConfig()",
    }
    norm_config = norm_map.get(config.norm_type, "RMSNormConfig()")

    # GatedDeltaNet-specific params
    n_v_heads_str = f"\n            n_v_heads={config.gdn_n_v_heads}," if config.gdn_n_v_heads else ""

    return f'''"""
{config.name} - OLMo-core GatedDeltaNet Configuration
{'=' * 60}
Race: {config.race}
Parameters: ~{config.param_str()}

Generated by The Elder Models V: LLMRIM
"Born of the Hist, fluid as water through roots..."

Architecture:
- Sequence Mixer: GatedDeltaNet (native SequenceMixer API)
- Linear Attention: O(n) complexity with gated delta rule
- Value Expansion: {config.gdn_expand_v}x
- Negative Eigenvalues: {"Allowed" if config.gdn_allow_neg_eigval else "Disabled"}
- Conv Size: {config.gdn_conv_size}
- Norm: {config.norm_type.name}
"""

from olmo_core.nn.transformer import (
    TransformerConfig,
    TransformerBlockConfig,
)
from olmo_core.nn.attention import GatedDeltaNetConfig
from olmo_core.nn.feed_forward import FeedForwardConfig
from olmo_core.nn.layer_norm import RMSNormConfig, LayerNormConfig, FusedRMSNormConfig, L2NormConfig
from olmo_core.nn.lm_head import LMHeadConfig


def build_{model_name.lower()}_config() -> TransformerConfig:
    """Build the {config.name} GatedDeltaNet model configuration.

    Uses olmo-core's native GatedDeltaNetConfig as the sequence mixer,
    providing O(n) linear attention with gated delta rule recurrence.
    The recurrent state has constant size (n_v_heads x head_k_dim x head_v_dim),
    independent of sequence length.
    """

    d_model = {config.n_embd}
    n_layers = {config.n_layers}
    n_heads = {config.n_heads}
    vocab_size = {config.vocab_size}
    max_seq_len = {config.seq_length}

    # Calculate MLP hidden dimension
    mlp_hidden = int(d_model * {config.mlp_ratio})
    mlp_hidden = ((mlp_hidden + 255) // 256) * 256  # Round to 256 for efficiency

    return TransformerConfig(
        d_model=d_model,
        n_layers=n_layers,
        vocab_size=vocab_size,

        # Block with GatedDeltaNet as native sequence mixer
        block=TransformerBlockConfig(
            sequence_mixer=GatedDeltaNetConfig(
                n_heads=n_heads,{n_v_heads_str}
                expand_v={config.gdn_expand_v},
                allow_neg_eigval={config.gdn_allow_neg_eigval},
                conv_size={config.gdn_conv_size},
            ),

            feed_forward=FeedForwardConfig(
                hidden_size=mlp_hidden,
                bias={config.mlp_bias},
                activation='silu',  # SwiGLU
            ),

            layer_norm={norm_config},
        ),

        # No RoPE needed - GatedDeltaNet handles position internally
        # via causal 1D convolutions and recurrent dynamics

        lm_head=LMHeadConfig(
            tie_weights={config.tie_embeddings},
        ),

        init_seed=42,
    )


# Build the configuration
config = build_{model_name.lower()}_config()

if __name__ == "__main__":
    # Build the model
    model = config.build()
    n_params = sum(p.numel() for p in model.parameters())
    print(f"{config.name}: {{n_params:,}} parameters")
    print(f"Recurrent state shape: n_v_heads x head_k_dim x head_v_dim")
    print(f"Constant memory regardless of sequence length!")
'''


def generate_fla_config(config: ModelConfig) -> str:
    """Generate FLA (Mamba/Mamba2) model configuration.

    Note: GatedDeltaNet now uses generate_gdn_config() with native SequenceMixer API.
    This function is for Mamba/Mamba2 which still use the FLA wrapper.
    """
    model_name = config.name.replace("-", "").replace(" ", "")

    # Determine FLA type (only Mamba variants now)
    fla_type_map = {
        SequenceModelType.MAMBA: "Mamba",
        SequenceModelType.MAMBA2: "Mamba2",
    }
    fla_type = fla_type_map.get(config.sequence_model, "Mamba2")

    return f'''"""
{config.name} - OLMo-core FLA Model Configuration
{'=' * 60}
Race: {config.race}
Parameters: ~{config.param_str()}

Generated by The Elder Models V: LLMRIM
"The Dwemer vanished, but their automatons remain..."

Architecture:
- Sequence Model: {config.sequence_model.name}
- FLA Type: {fla_type}
- Norm: {config.norm_type.name}
"""

from olmo_core.nn.fla import FLAConfig, FLABlock, FLAModelConfig
from olmo_core.nn.layer_norm import RMSNormConfig
from olmo_core.nn.lm_head import LMHeadConfig
from fla.layers import {fla_type}


def build_{model_name.lower()}_config():
    """Build the {config.name} FLA model configuration."""

    d_model = {config.n_embd}
    n_layers = {config.n_layers}
    vocab_size = {config.vocab_size}
    max_seq_len = {config.seq_length}

    # FLA layer configuration
    fla_config = FLAConfig(
        name="{fla_type}",
        kwargs=dict(
            d_model=d_model,
            d_state={config.mamba_d_state},
            d_conv={config.mamba_d_conv},
            expand={config.mamba_expand},
        ),
    )

    return FLAModelConfig(
        d_model=d_model,
        n_layers=n_layers,
        vocab_size=vocab_size,
        fla=fla_config,
        layer_norm=RMSNormConfig(),
        lm_head=LMHeadConfig(tie_weights={config.tie_embeddings}),
    )


# Build the configuration
config = build_{model_name.lower()}_config()

if __name__ == "__main__":
    # Build the model
    model = config.build()
    n_params = sum(p.numel() for p in model.parameters())
    print(f"{{config.name}}: {{n_params:,}} parameters")
'''


def generate_hybrid_config(config: ModelConfig) -> str:
    """Generate hybrid (attention + GatedDeltaNet) model configuration.

    Uses TransformerConfig with block_overrides to alternate between
    standard attention and GatedDeltaNet sequence mixers per layer.
    """
    model_name = config.name.replace("-", "").replace(" ", "")

    fla_layers_str = str(config.fla_layers) if config.fla_layers else "list(range(0, n_layers, 2))"

    # Determine attention backend
    backend_map = {
        AttentionBackend.TORCH: "AttentionBackend.torch",
        AttentionBackend.FLASH_2: "AttentionBackend.flash_2",
        AttentionBackend.FLASH_3: "AttentionBackend.flash_3",
        AttentionBackend.FLASH_4: "AttentionBackend.flash_4",
        AttentionBackend.TRANSFORMER_ENGINE: "AttentionBackend.te",
    }
    backend = backend_map.get(config.attention_backend, "AttentionBackend.torch")

    return f'''"""
{config.name} - OLMo-core Hybrid Model Configuration
{'=' * 60}
Race: {config.race}
Parameters: ~{config.param_str()}

Generated by The Elder Models V: LLMRIM
"The Falmer were twisted by darkness into something new..."

Architecture:
- Sequence Model: HYBRID (Attention + GatedDeltaNet)
- Attention Layers: {config.n_layers - len(config.fla_layers or [])} (standard softmax)
- GatedDeltaNet Layers: {len(config.fla_layers or [])} (linear attention)
- SequenceMixer API: Each layer independently configurable
- Norm: {config.norm_type.name}
"""

from olmo_core.nn.transformer import TransformerConfig, TransformerBlockConfig
from olmo_core.nn.attention import AttentionConfig, AttentionBackend, GatedDeltaNetConfig
from olmo_core.nn.feed_forward import FeedForwardConfig
from olmo_core.nn.layer_norm import RMSNormConfig
from olmo_core.nn.rope import RoPEConfig, RoPEType
from olmo_core.nn.lm_head import LMHeadConfig


def build_{model_name.lower()}_config():
    """Build the {config.name} hybrid model configuration.

    Uses block_overrides to assign GatedDeltaNetConfig as the sequence_mixer
    for specific layers, while other layers use standard AttentionConfig.
    This combines the long-range efficiency of linear attention with the
    precise recall of softmax attention.
    """

    d_model = {config.n_embd}
    n_layers = {config.n_layers}
    n_heads = {config.n_heads}
    n_kv_heads = {config.kv_heads}
    vocab_size = {config.vocab_size}
    max_seq_len = {config.seq_length}

    # Layers that use GatedDeltaNet instead of standard attention
    gdn_layers = {fla_layers_str}

    # Calculate MLP hidden dimension
    mlp_hidden = int(d_model * {config.mlp_ratio})
    mlp_hidden = ((mlp_hidden + 255) // 256) * 256

    # Shared feed-forward and norm configs
    ff_config = FeedForwardConfig(
        hidden_size=mlp_hidden,
        bias={config.mlp_bias},
        activation='silu',
    )

    # GatedDeltaNet sequence mixer for linear attention layers
    gdn_mixer = GatedDeltaNetConfig(
        n_heads=n_heads,
        expand_v={config.gdn_expand_v},
        allow_neg_eigval={config.gdn_allow_neg_eigval},
        conv_size={config.gdn_conv_size},
    )

    # Build block overrides: GatedDeltaNet layers get the linear mixer
    block_overrides = {{}}
    for layer_idx in gdn_layers:
        block_overrides[layer_idx] = TransformerBlockConfig(
            sequence_mixer=gdn_mixer,
        )

    return TransformerConfig(
        d_model=d_model,
        n_layers=n_layers,
        vocab_size=vocab_size,

        # Default block: standard attention
        block=TransformerBlockConfig(
            sequence_mixer=AttentionConfig(
                n_heads=n_heads,
                n_kv_heads=n_kv_heads,
                head_dim=d_model // n_heads,
                bias={config.attention_bias},
                qk_norm={config.qk_norm},
                backend={backend},
            ),
            feed_forward=ff_config,
            layer_norm=RMSNormConfig(),
        ),

        rope=RoPEConfig(
            type=RoPEType.default,
            theta={config.rope_theta},
        ),

        lm_head=LMHeadConfig(tie_weights={config.tie_embeddings}),

        # Override specific layers with GatedDeltaNet
        block_overrides=block_overrides,
    )


# Build the configuration
config = build_{model_name.lower()}_config()

if __name__ == "__main__":
    # Build the model
    model = config.build()
    n_params = sum(p.numel() for p in model.parameters())
    print(f"{{config.name}}: {{n_params:,}} parameters")
    print(f"Hybrid: {{len({fla_layers_str})}} GatedDeltaNet + {{n_layers - len({fla_layers_str})}} Attention layers")
'''


def generate_training_script(config: ModelConfig) -> str:
    """Generate a complete training script using OLMo-core."""
    model_name = config.name.replace("-", "").replace(" ", "")

    optimizer_config = ""
    if config.optimizer == Optimizer.ADAMW:
        optimizer_config = f"""
    optimizer=AdamWConfig(
        lr={config.learning_rate},
        weight_decay={config.weight_decay},
        betas=({config.beta1}, {config.beta2}),
    ),"""
    else:
        optimizer_config = f"""
    # Using Muon optimizer (custom implementation)
    optimizer=AdamWConfig(  # Placeholder - swap with Muon
        lr={config.learning_rate},
        weight_decay={config.weight_decay},
    ),"""

    return f'''"""
{config.name} - Training Script
{'=' * 60}
Generated by The Elder Models V: LLMRIM

This script sets up distributed training using OLMo-core.
Modify the data paths and hyperparameters as needed.
"""

import sys
from pathlib import Path

from olmo_core.config import DType
from olmo_core.distributed.parallel import DataParallelConfig, DataParallelType
from olmo_core.nn.transformer import TransformerConfig
from olmo_core.optim import AdamWConfig, CosineWithWarmupConfig
from olmo_core.train import TrainerConfig
from olmo_core.train.callbacks import (
    CheckpointerCallback,
    GarbageCollectorCallback,
    GPUMemoryMonitorCallback,
    GradClipperCallback,
    SchedulerCallback,
)


def build_trainer_config(
    model_config: TransformerConfig,
    run_name: str = "{model_name.lower()}",
    save_folder: str = "./checkpoints",
) -> TrainerConfig:
    """Build the training configuration."""

    return TrainerConfig(
        save_folder=save_folder,
        rank_microbatch_size=4,  # Adjust based on GPU memory
        metrics_collect_interval=10,
        cancel_check_interval=1,

        # Data parallelism
        data_parallel=DataParallelConfig(
            name=DataParallelType.fsdp,
            param_dtype=DType.bfloat16,
            reduce_dtype=DType.float32,
        ),
{optimizer_config}
        # Learning rate schedule
        scheduler=CosineWithWarmupConfig(
            warmup_steps=2000,
            t_max=100000,  # Total steps
            alpha_f=0.1,  # Final LR multiplier
        ),

        # Callbacks
        callbacks={{
            "lr_scheduler": SchedulerCallback(),
            "grad_clipper": GradClipperCallback(max_grad_norm=1.0),
            "gpu_monitor": GPUMemoryMonitorCallback(),
            "garbage_collector": GarbageCollectorCallback(),
            "checkpointer": CheckpointerCallback(
                save_interval=1000,
                ephemeral_save_interval=100,
            ),
        }},

        # Compilation (optional, for speed)
        compile_model=True,
    )


if __name__ == "__main__":
    from {model_name.lower()}_config import config as model_config

    trainer_config = build_trainer_config(model_config)

    print(f"Training configuration for {config.name}:")
    print(f"  - Model: ~{config.param_str()} parameters")
    print(f"  - Optimizer: {config.optimizer.name}")
    print(f"  - Learning rate: {config.learning_rate}")
'''


def generate_model_code(config: ModelConfig) -> str:
    """Generate complete model code based on architecture type."""
    if config.sequence_model == SequenceModelType.GATED_DELTANET:
        # Use native GatedDeltaNetConfig via SequenceMixer API
        return generate_gdn_config(config)
    elif config.is_mamba and not config.is_hybrid:
        # Mamba/Mamba2 still use FLA wrapper
        return generate_fla_config(config)
    elif config.is_hybrid:
        return generate_hybrid_config(config)
    else:
        return generate_olmo_config(config)


def generate_full_package(config: ModelConfig) -> dict[str, str]:
    """Generate a complete package with config, model, and training script."""
    model_name = config.name.replace("-", "").replace(" ", "").lower()

    return {
        f"{model_name}_config.py": generate_model_code(config),
        f"{model_name}_train.py": generate_training_script(config),
        "README.md": _generate_readme(config),
    }


def _generate_readme(config: ModelConfig) -> str:
    """Generate a README for the model."""
    # Determine sequence mixer description
    if config.sequence_model == SequenceModelType.GATED_DELTANET:
        mixer_desc = "GatedDeltaNet (native SequenceMixer, O(n) linear attention)"
    elif config.is_mamba:
        mixer_desc = f"{config.sequence_model.name} (FLA wrapper)"
    elif config.is_hybrid:
        fla_count = len(config.fla_layers) if config.fla_layers else 0
        mixer_desc = f"Hybrid ({fla_count} GatedDeltaNet + {config.n_layers - fla_count} Attention)"
    else:
        mixer_desc = f"{config.attention_type.name} (SequenceMixer API)"

    return f"""# {config.name}

Generated by **The Elder Models V: LLMRIM**

*"Fus Ro Brrr... Your training begins."*

## Architecture

| Attribute | Value |
|-----------|-------|
| Race | {config.race} |
| Parameters | ~{config.param_str()} |
| Sequence Mixer | {mixer_desc} |
| MLP | {config.mlp_type.name} |
| Block | {config.block_type.name} |
| Norm | {config.norm_type.name} |
| Position | {config.position_encoding.name} |
| Context Length | {config.seq_length:,} |
| Vocabulary | {config.vocab_size:,} |

## Configuration

- **Embedding Dimension**: {config.n_embd}
- **Layers**: {config.n_layers}
- **Attention Heads**: {config.n_heads}
- **KV Heads**: {config.kv_heads}

{f"## Mixture of Experts" if config.is_moe else ""}
{f"- **Experts**: {config.num_experts}" if config.is_moe else ""}
{f"- **Experts per Token**: {config.experts_per_token}" if config.is_moe else ""}

{f"## GatedDeltaNet" if config.sequence_model == SequenceModelType.GATED_DELTANET else ""}
{f"- **Value Expansion**: {config.gdn_expand_v}x" if config.sequence_model == SequenceModelType.GATED_DELTANET else ""}
{f"- **Allow Neg Eigenvalues**: {config.gdn_allow_neg_eigval}" if config.sequence_model == SequenceModelType.GATED_DELTANET else ""}
{f"- **Conv Size**: {config.gdn_conv_size}" if config.sequence_model == SequenceModelType.GATED_DELTANET else ""}

## Usage

```python
from {config.name.replace('-', '').replace(' ', '').lower()}_config import config

# Build the model
model = config.build()

# Count parameters
n_params = sum(p.numel() for p in model.parameters())
print(f"Parameters: {{n_params:,}}")
```

## Training

```bash
# Single GPU
python {config.name.replace('-', '').replace(' ', '').lower()}_train.py

# Multi-GPU with torchrun
torchrun --nproc_per_node=8 {config.name.replace('-', '').replace(' ', '').lower()}_train.py
```

## Requirements

- Python 3.10+
- PyTorch 2.0+
- ai2-olmo-core >= 2.4.0
- flash-attn (optional, for Flash Attention backends)
- fla (for Mamba/Mamba2 models only; GatedDeltaNet uses native olmo-core)

---

*Generated on {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}*
"""
